- platform: generic
  still_image_url: !secret camera1_still_image_url
  stream_source: !secret camera1_stream_source
  name: Front Door
  username: admin
  password: !secret camera_doorbell_password
  framerate: 12
  authentication: basic
- platform: generic
  still_image_url: !secret camera2_still_image_url
  stream_source: !secret camera2_stream_source
  name: Driveway One
  username: hass
  password: !secret camera_nvr_password
  authentication: digest
- platform: generic
  still_image_url: !secret camera3_still_image_url
  stream_source: !secret camera3_stream_source
  name: Driveway Two
  username: hass
  password: !secret camera_nvr_password
  authentication: digest
- platform: generic
  still_image_url: !secret camera4_still_image_url
  stream_source: !secret camera4_stream_source
  name: Back Gate
  username: hass
  password: !secret camera_nvr_password
  authentication: digest
- platform: generic
  still_image_url: !secret camera5_still_image_url
  stream_source: !secret camera5_stream_source
  name: Side Yard
  username: hass
  password: !secret camera_nvr_password
  authentication: digest
- platform: local_file
  file_path: /home/homeassistant/.homeassistant/www/tmp/front_door_latest.jpg
  name: Front Door Processed
- platform: local_file
  file_path: /home/homeassistant/.homeassistant/www/tmp/back_yard_latest.jpg
  name: Back Yard Processed
#- platform: ffmpeg
#  input: !secret camera_url_1
#  name: Front Door
#  extra_arguments: -pred 1 -q:v 2
#- platform: ffmpeg
#  input: !secret camera_url_2
#  extra_arguments: -pred 1 -q:v 2
#  name: driveway one
#- platform: ffmpeg
#  input: !secret camera_url_3
#  extra_arguments: -pred 1 -q:v 2
#  name: driveway two
#- platform: ffmpeg
#  input: !secret camera_url_4
#  extra_arguments: -pred 1 -q:v 2
#  name: back gate
#- platform: ffmpeg
#  input: !secret camera_url_5
#  extra_arguments: -pred 1 -q:v 2
#  name: side yard"